minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - devalue
  - svelte
  - "@sveltejs/*"
  - "@sveltia/*"
  - lexical
  - "@lexical/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - es5-ext
  - esbuild
  - svelte-preprocess

overrides:
  esbuild@<=0.24.2: ">=0.25.0"
